name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: apt-get update
    - name: dependencies
      run: sudo apt-get install libsdl2-dev -y
    - name: make
      run: make
